local router_helper = require("main.router_helper")

function init(self)
    msg.post(".", "acquire_input_focus")
end

function on_message(self, message_id, message, sender)
    if message_id == hash("scene_input") then
        local world, level = message.input.world, message.input.level
        msg.post("gui", "set_text", {text = "You've failed level " .. world .. "-" .. level})
    elseif message_id == hash("ok") then
        router_helper.close_scene()
    end
end
