function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("mouse") and action.released then
		if gui.pick_node(gui.get_node("start"), action.x, action.y) then
			msg.post("controller#script", "start")
		elseif gui.pick_node(gui.get_node("settings"), action.x, action.y) then
			msg.post("controller#script", "settings")
		end
	end
end
