local router_helper = require("main.router_helper")

function init(self)
    msg.post(".", "acquire_input_focus")
end

function on_message(self, message_id, message, sender)
    if message_id == hash("start") then
        router_helper.close_scene()
    elseif message_id == hash("settings") then
        msg.post("gui", "disable")
        router_helper.popup("settings")
    elseif message_id == hash("scene_popped") then
        msg.post("gui", "enable")
    end
end
