function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_message(self, message_id, message, sender)
    if message_id == hash("set_text") then
        gui.set_text(gui.get_node("text/text"), message.text)
    end
end

function on_input(self, action_id, action)
	if action_id == hash("mouse") and action.released then
		if gui.pick_node(gui.get_node("ok/box"), action.x, action.y) then
			msg.post("controller#script", "ok")
		end
	end
end
