-- Defold Router Demo Project
--
-- © 2016 Roman "Megus" Petrov, Wise Hedgehog Studio.
-- https://wisehedgehog.studio, https://megus.org

function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("mouse") and action.released then
		if gui.pick_node(gui.get_node("close/box"), action.x, action.y) then
			msg.post("controller#script", "close")
		end
	end
end
